# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: b0f11fe246ae49c7a3791009753d2148b97cb677
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: name-tests-test
    -   id: mixed-line-ending
    -   id: check-ast
    -   id: check-case-conflict

-   repo: https://github.com/asottile/pyupgrade
    rev: 45cdd60115e2fbab3bc8b1046a42c7302b2c0c8b
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: 336fdd7c3cab698ead0b1c95157b9e74d3906b62
    hooks:
    -   id: clang-format
        args: [--style=Google]

-   repo: https://github.com/psf/black
    rev: a552f7096a9f6e016c9bb1df1e0a77a17caeec1c
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 45699b61ae4522864c60480c80d7c2ffb952d52e
    hooks:
    -   id: flake8
